### ISSUE TITLE
Is there a way to visualise activation in three dimension.

### ISSUE THREAD

**Issue by shivam-deepcompute** [philipperemy/keras-visualize-activations#6]
Hi @philipperemy ,
Thank you for making me understand #5 .
I was thinking to visualise the activation in 3D map. Is there a way. Like for example,  something like this.
![downsampled](https://user-images.githubusercontent.com/33828942/40599228-c85013c8-6269-11e8-9294-6b358b8fc229.png)

I am a novice, don't know if this question fits here.

**Comment by philipperemy** [comment]
If you want to visualize something in 3D, you need to have a tensor of 3 dimensions to visualize.

The keras visualization library only returns you numpy arrays.

You're free to do what you want with those arrays.

You could use matplotlib to draw 3D plots: https://matplotlib.org/1.5.1/mpl_toolkits/mplot3d/tutorial.html

You can also dump those arrays into NPY files (using numpy.save) and read them in MATLAB: https://github.com/kwikteam/npy-matlab

**Comment by shivam-deepcompute** [comment]
Thanks to your reply. Will try to explore that part.

**Comment by philipperemy** [comment]
Welcome!
