### ISSUE TITLE
Extraction of the highest/strongest activation map

### ISSUE THREAD

**Issue by abhigoku10** [philipperemy/keras-visualize-activations#7]
@philipperemy @zhhongzhi  Hi thanks for the code just wanted know , in a given layer for number of filters how to extract / visualize the filter which has the maximum magnitude or strongest activation map in the given filter layer . Can you pls point at code level too

**Comment by philipperemy** [comment]
@abhigoku10 

Consider one image, MNIST and LeNet. The activations look like this:

```
(1, 26, 26, 32)
(1, 24, 24, 64)
(1, 12, 12, 64)
(1, 12, 12, 64)
(1, 9216)
(1, 128)
(1, 128)
(1, 10) # softmax output!
```

Let's consider the second layer: (1, 24, 24, 64)

In that case you can do something like that:

```
a = np.random.uniform(size=(20, 24, 24, 64)) # in your case plug the real matrix from the script.
np.argmax(np.max(a, axis=(1, 2)), axis=1) # will give you the index of the filter that contains the highest value. In that case the shape will be 20 because you have a batch of 20.
```
